name: krisdanto
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  background_fetch: ^0.5.5
  carousel_slider: ^3.0.0
  carousel_pro: ^1.0.0
  cached_network_image: ^2.5.0
  circular_menu: ^1.1.2
  cloud_firestore: ^0.14.1+3
  cloud_functions: ^0.6.0+1
  confirm_dialog: ^0.1.1
  # cupertino_icons: ^1.0.0
  
  dots_indicator: ^1.2.0
  dropdown_search: ^0.4.9
  email_validator: ^1.0.6
  enum_to_string: ^1.0.14
  equatable: ^1.2.5
  firebase_auth: ^0.18.1+2
  firebase_core: ^0.5.3
  firebase_database: ^4.4.0
  firebase_storage: ^5.1.0
  firebase_messaging: ^7.0.3
  flutter_advanced_networkimage: ^0.7.0
  flutter_animarker: ^1.0.0
  flutter_bloc: ^6.0.1
  flutter_chips_input: ^1.9.4
  flutter_date_pickers: ^0.1.10
  flutter_launcher_icons: ^0.8.0
  flutter_rating_bar: ^3.0.1+1
  flutter_rounded_date_picker: ^1.0.5+1
  flutter_screenutil: ^4.0.2+1
  flutter_spinbox: ^0.3.1+2
  flutter_spinkit: ^4.1.2
  flutter_svg: ^0.19.0
  flutter_timeline: ^0.1.1+13
  fluttertoast: ^7.1.6
  flushbar: ^1.10.4
  font_awesome_flutter: ^8.5.0
  gallery_saver: ^2.0.3
  geocoding: ^1.0.5
  geocoder: ^0.2.1
  geoflutterfire: ^2.2.1
  geolocator: ^6.1.13
  get: ^3.24.0
  google_fonts: ^1.1.1
  google_maps_flutter: ^1.0.6
  google_maps_place_picker: ^1.0.1
  http: ^0.12.0+4
  image_gallery_saver: ^1.6.8
  image_picker: ^0.6.7+4
  intl: ^0.16.1
  jiffy: ^3.0.1
  loading_indicator: ^1.2.0
  localstorage: ^3.0.6+9
  # location: ^1.4.1
  network_to_file_image: ^2.3.6
  package_info: ^0.4.0+16
  path: ^1.7.0
  path_provider: ^1.6.21
  path_provider_platform_interface: ^1.0.1
  permission_handler: ^5.0.1+1
  progress_indicators: ^0.1.2
  progress_indicator_button: ^0.0.3
  provider: ^4.1.2
  qr_flutter: ^3.2.0
  router_management: ^1.3.3
  share: ^0.6.5+4
  shared_preferences: ^0.5.7+3
  shimmer: ^1.1.2
  # simple_permissions: ^0.1.9
  splashscreen: ^1.3.5
  textfield_search: ^0.8.0
  timeago: ^2.0.29
  timeline_tile: ^1.0.0
  time_range_picker: ^1.1.1
  uuid: 2.2.2


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  flutter_svg: ^0.18.0
  intl: ^0.17.0-nullsafety.2
  path_provider: ^1.6.21
  

     


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
